### PR TITLE
Merge MVC to non release branch for Team Approval

### PR DESCRIPTION
**Pull request by TraceLarson**
If all approve I will merge into Non-Release-Dev-Check then delete the branch. We will continue to work from Dev branch going forward.

### CODE REVIEW

**Comment by hughesd22** [comment]
Why the branch name "Non-Release-Dev-Check"? @TraceLarson 

I'm not clear on what this branch's purpose is. Shouldn't we create a Pull Request from dev into a release branch and discuss changes on that PR?

Edit: grammar

**Comment by hughesd22** [comment]
As far as the MVC structure goes, it looks good to me.

**Review by hughesd22 — APPROVED** [review]

**Comment by TraceLarson** [comment]
@hughesd22 I am going to delete the Non-Release-Dev-Check. Its just to accomplish a Pull Request workflow.

**Comment by TraceLarson** [comment]
@hughesd22 I included Axios because we may want to pull some information from another API at some point. Fetch is always available, but I am partial to Axios at the moment.

**Comment by hughesd22** [comment]
@TraceLarson in the Pull Request workflow, you create a release branch off develop, then open a Pull Request from that release branch into master. Then we would have this discussion on that PR.

**Pull request merged**
